root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/strict-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - ./tsconfig.json
    - ./tsconfig.node.json
  tsconfigRootDir: .
plugins:
  - react-refresh
settings:
  react:
    version: detect
rules:
  # https://github.com/ArnaudBarre/eslint-plugin-react-refresh
  'react-refresh/only-export-components':
    - warn
    - allowConstantExport: true

  '@typescript-eslint/consistent-type-definitions':
    - error
    - type
